config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :numbers
    resources :notifications
    resources :items

    root to: "numbers#index"
  end

  resources :items
  resources :numbers
  post 'receive', to: 'items#create'
  #root "articles#index"
end

app/models/number.rb
class Number < ApplicationRecord
  HOURS_TO_SEND = [10, 12, 14, 16, 18, 20]
  has_many :items

  def self.send_for_each
    all.each(&:send_out_items)
  end

  def send_out_items
    return if items.not_complete.empty?

    message = items.not_complete.items_stringified_for_message

    Time.use_zone('Eastern Time (US & Canada)') do
      return unless HOURS_TO_SEND.include?(Time.zone.now.hour)

      ItemNotification
        .with(message: message)
        .deliver(self)
    end
  end
end

app/controllers/admin/numbers_controller.rb
module Admin
  class NumbersController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/numbers_controller.rb
class NumbersController < ApplicationController
  before_action :set_number, only: %i[ show edit update destroy ]

  # GET /numbers or /numbers.json
  def index
    @numbers = Number.all
  end

  # GET /numbers/1 or /numbers/1.json
  def show
  end

  # GET /numbers/new
  def new
    @number = Number.new
  end

  # GET /numbers/1/edit
  def edit
  end

  # POST /numbers or /numbers.json
  def create
    @number = Number.new(number_params)

    respond_to do |format|
      if @number.save
        format.html { redirect_to number_url(@number), notice: "Number was successfully created." }
        format.json { render :show, status: :created, location: @number }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @number.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /numbers/1 or /numbers/1.json
  def update
    respond_to do |format|
      if @number.update(number_params)
        format.html { redirect_to number_url(@number), notice: "Number was successfully updated." }
        format.json { render :show, status: :ok, location: @number }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @number.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /numbers/1 or /numbers/1.json
  def destroy
    @number.destroy

    respond_to do |format|
      format.html { redirect_to numbers_url, notice: "Number was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_number
      @number = Number.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def number_params
      params.require(:number).permit(:number)
    end
end

app/helpers/numbers_helper.rb
module NumbersHelper
end

app/views/numbers/_form.html.erb
<%= form_with(model: number) do |form| %>
  <% if number.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(number.errors.count, "error") %> prohibited this number from being saved:</h2>

      <ul>
        <% number.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :number, style: "display: block" %>
    <%= form.text_field :number %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/numbers/_number.html.erb
<div id="<%= dom_id number %>">
  <p>
    <strong>Number:</strong>
    <%= number.number %>
  </p>

</div>

app/views/numbers/edit.html.erb
<h1>Editing number</h1>

<%= render "form", number: @number %>

<br>

<div>
  <%= link_to "Show this number", @number %> |
  <%= link_to "Back to numbers", numbers_path %>
</div>

app/views/numbers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Numbers</h1>

<div id="numbers">
  <% @numbers.each do |number| %>
    <%= render number %>
    <p>
      <%= link_to "Show this number", number %>
    </p>
  <% end %>
</div>

<%= link_to "New number", new_number_path %>

app/views/numbers/new.html.erb
<h1>New number</h1>

<%= render "form", number: @number %>

<br>

<div>
  <%= link_to "Back to numbers", numbers_path %>
</div>

app/views/numbers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @number %>

<div>
  <%= link_to "Edit this number", edit_number_path(@number) %> |
  <%= link_to "Back to numbers", numbers_path %>

  <%= button_to "Destroy this number", @number, method: :delete %>
</div>